### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by megan07**

### CODE REVIEW

**Review by shuyama1 — COMMENTED** [review]
Should this be release 4.24.0?

**Comment by megan07** [comment]
Oh yea! Good catch, thanks!!

**Comment by shuyama1** [comment]
Probably the 4.23.0 changelog was merged after the release was cut.

**Comment by megan07** [comment]
Oh, yes, you're right! I will update this on Monday! Sorry about that!

**Pull request closed without merging**
