### PR TITLE
add certificate_map to compute_target_https_proxy

### PR DESCRIPTION
**Pull request by MoinTom**
related to issue https://github.com/hashicorp/terraform-provider-google/issues/11037

Add `certificate_map` option to `compute_target_https_proxy` in order to support  new certificate-manager (with wildcard support).

Relevant Documentation for this new field/feature:
[How To Cert Manager](https://cloud.google.com/certificate-manager/docs/deploy-google-managed)
[setCertificateMap](https://cloud.google.com/compute/docs/reference/rest/beta/targetHttpsProxies/setCertificateMap)

### CODE REVIEW

**Comment by MoinTom** [comment]
I am not sure about some of my changes. Specially the new `LocationFieldValue` type, which was sort of required for the (new?) path format that is used by certificateMaps resources.

**Comment by rileykarson** [comment]
@megan07: I suspect the reviewer lottery only applies to "Ready for Review" PRs and not drafts, this doesn't seem to have had one assigned!

**Comment by shuyama1** [comment]
@MoinTom Thanks for making the changes! Would you mind making this change against https://github.com/GoogleCloudPlatform/magic-modules following the instruction [here](https://github.com/GoogleCloudPlatform/magic-modules#making-changes-to-resources)

**Comment by MoinTom** [comment]
@shuyama1 oh, totally overlooked the fact that those files are generated. 

I can create a short PR with the added `certificate_map` field, however it seems like it's not possible to add `certificate_map` without first adding a `CertificateMap` resource. At least when i tried using the (correct) `ResourceRef`-Type. It works with the simpler `String`-Type, that doesn't offer link validation and self-discovery (name -> selfLink), but it should at least be usable for the time being. 

However i noticed that someone already implemented the `CertificateManager`, but it got removed: https://github.com/GoogleCloudPlatform/magic-modules/pull/4968
Maybe resurrecting this would be the smarter first move here.

**Comment by MoinTom** [comment]
I will close this PR since changes are required upstream.

**Pull request closed without merging**
