### PR TITLE
Downgraded bigtable to 1.7.1

### PR DESCRIPTION
**Pull request by melinath**
Reverts https://github.com/hashicorp/terraform-provider-google-beta/pull/3259

### CODE REVIEW

**Comment by melinath** [comment]
Test run: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/188497

**Comment by rileykarson** [comment]
I think you'll need to bust some quota to pass the tests!

**Review by rileykarson — APPROVED** [review]

**Comment by melinath** [comment]
Going ahead with merge; I'll check the nightly test run in the morning.

**Comment by melinath** [comment]
Nightly build failed due to quota issues - here's a run on master: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/188649

**Comment by melinath** [comment]
It looks like we could go up to 1.8.0 but for now I'm happy to leave it here.

**Pull request merged**
