### PR TITLE
enable rbac for data_fusion_instance

### PR DESCRIPTION
**Pull request by Guimove**
Google as recently enabled an RBAC option for Data fusion instance. We want to use it on a big project to share an instance with multiple tenants. 
So I'm happy to add my magic sauce to make it work. 

Hope all is ok.

Fix https://github.com/hashicorp/terraform-provider-google/issues/9065

### CODE REVIEW

**Comment by slevenick** [comment]
Hmmmm, do you have a link to where this was announced? I can't find this field on the API docs: https://cloud.google.com/data-fusion/docs/reference/rest/v1beta1/projects.locations.instances#Instance

We use a code generator (https://github.com/GoogleCloudPlatform/magic-modules) to generate this file, so the change will need to be made there. It should be fairly simple assuming this field is publicly available. I can help with that change as well

**Comment by Guimove** [comment]
My bad, it seems it was not announced, seems we are in a preview.
But as we are doing everything with terraform, we are actually blocked.

Do you think we can continue to work on this or wait for public announcement ? 
It's already present in the GO client, for example https://github.com/googleapis/google-api-go-client/blob/9c02ff42de049ba27fb380e5660276ecbe0315a2/datafusion/v1beta1/datafusion-api.json#L959

I'll check tomorrow for the magic module.

Thanks,

**Comment by slevenick** [comment]
I'll ask around

**Comment by Guimove** [comment]
Hey, do you have any feedback ?

**Comment by SarahFrench** [comment]
The upstream issue (https://github.com/hashicorp/terraform-provider-google/issues/9065) has been closed by this PR: https://github.com/GoogleCloudPlatform/magic-modules/pull/6633

Closing this PR as stale/superseded

**Pull request closed without merging**
